name: restock_ai_app
description: "An AI Assistant Stock."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI & FONTS ---
  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.0
  phosphor_flutter: ^2.1.0
  fl_chart: ^0.71.0

  # --- STATE MANAGEMENT ---
  flutter_riverpod: ^2.6.1

  # --- BACKEND & NETWORK ---
  supabase_flutter: ^2.12.0
  http: ^1.2.1  

  # --- UTILITIES ---
  intl: ^0.20.2
  url_launcher: ^6.3.2 
  showcaseview: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0

  # --- HARDWARE & FILES ---
  camera: ^0.11.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  path: ^1.9.0
  pdf: ^3.10.8            
  printing: ^5.13.2       
  image: ^4.2.0 
  flutter_dotenv: ^6.0.0
  http_parser: ^4.1.2
  image_cropper: ^5.0.0
  print_bluetooth_thermal: ^1.1.1
  esc_pos_utils_plus: ^2.0.4
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png" 
  min_sdk_android: 21 

flutter_native_splash:
  color: "#FFFFFF" 
  image: "assets/splash.png"
  android_12: 
    image: "assets/splash.png"
    icon_background_color: "#FFFFFF"